"""add_requirement_documents_table

Revision ID: 4e65e2347e14
Revises: 3a237ec14c38
Create Date: 2026-04-29 18:36:50.984438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e65e2347e14'
down_revision: Union[str, None] = '3a237ec14c38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requirement_documents',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='parsed', nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirement_documents_id'), 'requirement_documents', ['id'], unique=False)
    op.create_index(op.f('ix_requirement_documents_project_id'), 'requirement_documents', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_requirement_documents_project_id'), table_name='requirement_documents')
    op.drop_index(op.f('ix_requirement_documents_id'), table_name='requirement_documents')
    op.drop_table('requirement_documents')
    # ### end Alembic commands ###
