"""add_ai_reviews_table

Revision ID: cd89345db2e1
Revises: 4e65e2347e14
Create Date: 2026-04-29 18:42:02.942123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd89345db2e1'
down_revision: Union[str, None] = '4e65e2347e14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_reviews',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=False),
    sa.Column('llm_config_id', sa.UUID(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('dimensions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('issues', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('review_time_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['requirement_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['llm_config_id'], ['llm_configs.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_reviews_document_id'), 'ai_reviews', ['document_id'], unique=False)
    op.create_index(op.f('ix_ai_reviews_id'), 'ai_reviews', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_reviews_id'), table_name='ai_reviews')
    op.drop_index(op.f('ix_ai_reviews_document_id'), table_name='ai_reviews')
    op.drop_table('ai_reviews')
    # ### end Alembic commands ###
