"""add_testcase_modules_and_generation_batches

Revision ID: d80326b76bad
Revises: fce3a67fa330
Create Date: 2026-04-29 19:41:55.032601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd80326b76bad'
down_revision: Union[str, None] = 'fce3a67fa330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('testcase_modules',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['testcase_modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testcase_modules_id'), 'testcase_modules', ['id'], unique=False)
    op.create_index(op.f('ix_testcase_modules_parent_id'), 'testcase_modules', ['parent_id'], unique=False)
    op.create_index(op.f('ix_testcase_modules_project_id'), 'testcase_modules', ['project_id'], unique=False)
    op.create_table('ai_generation_batches',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('llm_config_id', sa.UUID(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='generating', nullable=False),
    sa.Column('generated_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('accepted_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('generation_time_ms', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['requirement_documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['llm_config_id'], ['llm_configs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_generation_batches_id'), 'ai_generation_batches', ['id'], unique=False)
    op.create_index(op.f('ix_ai_generation_batches_project_id'), 'ai_generation_batches', ['project_id'], unique=False)
    op.create_table('testcases',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('precondition', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('source', sa.String(length=30), server_default='manual', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('generation_batch_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['generation_batch_id'], ['ai_generation_batches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['module_id'], ['testcase_modules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testcases_id'), 'testcases', ['id'], unique=False)
    op.create_index(op.f('ix_testcases_module_id'), 'testcases', ['module_id'], unique=False)
    op.create_index(op.f('ix_testcases_project_id'), 'testcases', ['project_id'], unique=False)
    op.create_table('testcase_steps',
    sa.Column('testcase_id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.SmallInteger(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['testcase_id'], ['testcases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_testcase_steps_id'), 'testcase_steps', ['id'], unique=False)
    op.create_index(op.f('ix_testcase_steps_testcase_id'), 'testcase_steps', ['testcase_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_testcase_steps_testcase_id'), table_name='testcase_steps')
    op.drop_index(op.f('ix_testcase_steps_id'), table_name='testcase_steps')
    op.drop_table('testcase_steps')
    op.drop_index(op.f('ix_testcases_project_id'), table_name='testcases')
    op.drop_index(op.f('ix_testcases_module_id'), table_name='testcases')
    op.drop_index(op.f('ix_testcases_id'), table_name='testcases')
    op.drop_table('testcases')
    op.drop_index(op.f('ix_ai_generation_batches_project_id'), table_name='ai_generation_batches')
    op.drop_index(op.f('ix_ai_generation_batches_id'), table_name='ai_generation_batches')
    op.drop_table('ai_generation_batches')
    op.drop_index(op.f('ix_testcase_modules_project_id'), table_name='testcase_modules')
    op.drop_index(op.f('ix_testcase_modules_parent_id'), table_name='testcase_modules')
    op.drop_index(op.f('ix_testcase_modules_id'), table_name='testcase_modules')
    op.drop_table('testcase_modules')
    # ### end Alembic commands ###
